### PR TITLE
Created new property, daoAccess.skipTotalCount

### PR DESCRIPTION
**Pull request by tggagne**
This is a better solution that was submitted earlier today.  Rather than just skipping the row count, the property allows users to decide whether they want it calculated and reported in progress updates or not.

The default value is true.

### CODE REVIEW

**Comment by diracz** [comment]
Looks good, except that you included the DataSource class in this pull. Can you remove that file, so it can get merged?

**Comment by tggagne** [comment]
Hmm.  I didn't push DataSource until today, and the pull request was 
from yesterday or this AM, wasn't it?

So, if I need to remove it are you suggesting I revert the commit? Sorry 
for the newbie questions--I'm not yet confident in my fork/pull moves.

**Comment by tggagne** [comment]
I'm looking again at the pull request -- that was submitted 23 hours 
ago.  Why are commits I made this afternoon included in it?

Can I submit another pull request from the commit before DataSource?

**Comment by diracz** [comment]
I'm not an expert on github by any means, but I think the basic idea is to folk per feature, so that you don't get into multiple features on the same fork like here. 
You can either revert the new file (of course, create another fork and put the new file there for the encrypt password feature), or do something like this to split commit:
http://stackoverflow.com/questions/12660839/pull-request-for-only-certain-files-commits

**Comment by tggagne** [comment]
Ok.  This pull request can be killed.  I've submitted request #70.

**Comment by tggagne** [comment]
I think I figured it out.  See Pull request #70. I closed #69.

**Pull request closed without merging**
